application: regexplanet-php
version: 1
runtime: php55
api_version: 1
env_variables:
  COMMIT: dev
  LASTMOD: dev
handlers:
- url: /robots.txt
  static_files: www/robots.txt
  upload: www/robots.txt
- url: /favicon.ico
  static_files: www/favicon.ico
  upload: www/favicon.ico
- url: /favicon.svg
  static_files: www/favicon.svg
  upload: www/favicon.svg
- url: /status.php
  script: www/status.php
- url: /status.json
  script: www/status.php
- url: /test.php
  script: www/test.php
- url: /
  script: www/index.php
- url: /phpinfo.php
  script: www/phpinfo.php
