application: regexplanet-php
version: 1
runtime: php
api_version: 1

handlers:
- url: /robots.txt
  static_files: www/robots.txt
  upload: www/robots.txt

- url: /favicon.ico
  static_files: www/favicon.ico
  upload: www/favicon.ico

- url: /status.php
  script: www/status.php

- url: /test.php
  script: www/test.php

- url: /
  script: www/index.php

- url: /phpinfo.php
  script: www/phpinfo.php
